<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Offre;
use AppBundle\Entity\User;
use AppBundle\Entity\TypeOffre;

/**
 * OffreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreRepository extends \Doctrine\ORM\EntityRepository {

    public function getReservations(Offre $offre) {
        $query = $this->getEntityManager()
                ->createQuery("SELECT r.date
                              FROM AppBundle:Reservation r
                              JOIN r.offre o
                              WHERE o.id = :id");

        $query->setParameter('id', $offre->getId());

        return $query->getResult();
    }

    public function getOffresByUser(User $user) {
        $query = $this->getEntityManager()
                ->createQuery("SELECT o
                              FROM AppBundle:Offre o
                              JOIN o.auteur a
                              WHERE a.id != :id");

        $query->setParameter('id', $user->getId());

        return $query->getResult();
    }

    public function findByUserAndType(User $user, TypeOffre $type) {
        $query = $this->getEntityManager()
                ->createQuery("SELECT o
                              FROM AppBundle:Offre o
                              JOIN o.type t 
                              JOIN o.auteur a
                              WHERE t.id = :type_id 
                              AND a.id != :user_id");

        $query->setParameter('type_id', $type->getId());
        $query->setParameter('user_id', $user->getId());

        return $query->getResult();
    }
}
