<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Offre;
use AppBundle\Entity\User;

/**
 * OffreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreRepository extends \Doctrine\ORM\EntityRepository {

    public function getReservations(Offre $offre) {
        $query = $this->getEntityManager()
                ->createQuery("SELECT r.date
                              FROM AppBundle:Reservation r
                              JOIN r.offre o
                              WHERE o.id = :id");

        $query->setParameter('id', $offre->getId());

        return $query->getResult();
    }

    public function getOffresByUser(User $user) {
        $query = $this->getEntityManager()
                ->createQuery("SELECT o
                              FROM AppBundle:Offre o
                              JOIN o.auteur a
                              WHERE a.id != :id");

        $query->setParameter('id', $user->getId());

        return $query->getResult();
    }

}
