<?php

namespace AppBundle\Repository;

/**
 * TypeOffreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeOffreRepository extends \Doctrine\ORM\EntityRepository
{
}
